---
apiVersion: v1
data:
  sec: Zm9vYmFyCg==
kind: Secret
metadata:
  name: sec
type: Opaque

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: stevemcquaid/hello-go:v5
          ports:
            - containerPort: 8080
          env:
            - name: FOO
              valueFrom:
                secretKeyRef:
                  name: sec
                  key: sec